<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Netchex-015" name="login" tests="1" failures="1" timestamp="27 May 2019 03:53:10 GMT" time="7.346" errors="0">
  <testcase name="LoginToApplication" time="5.607" classname="MDM.Automation_Test.SampleTest">
    <failure type="junit.framework.AssertionFailedError" message="Login Failed">
      <![CDATA[junit.framework.AssertionFailedError: Login Failed
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at MDM.Automation_Test.SampleTest.LoginToApplication(SampleTest.java:30)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- LoginToApplication -->
</testsuite> <!-- login -->
